let list = [
  {
    _id: 1,
    title: '14K/18K 허니 벌집2 헥사곤 심플 반지',
    img: 'image1.jpg',
    price: '185000',
    category: 'new',
    discount: '5',
  },
  {
    _id: 2,
    title: '14K/18K 마닐드 하트 드롭 큐빅 원터치 귀걸이',
    img: 'image2.jpg',
    price: '126250',
    category: 'top',
    discount: '31',
  },
  {
    _id: 3,
    title: '14k 데일리 심플 볼귀걸이 시리즈',
    img: 'image3.jpg',
    price: '30000',
    category: 'top',
    discount: '45',
  },
  {
    _id: 4,
    title: '14k/18k 데일리 더블링 목걸이',
    img: 'image4.jpg',
    price: '318000',
    category: 'new',
    discount: '42',
  },
  {
    _id: 5,
    title: '14K/18K 네쥬 T라인 원터치 링 귀찌 귀걸이',
    img: 'image5.jpg',
    price: '58000',
    category: 'new',
    discount: '0',
  },
  {
    _id: 6,
    title: '14k/18k 티얼스 라운드 큐빅 여성 체인 목걸이',
    img: 'image6.jpg',
    price: '310000',
    category: 'top',
    discount: '5',
  },
  {
    _id: 7,
    title: '블링 스타피쉬 헤어핀',
    img: 'image7.jpg',
    price: '24000',
    category: 'new',
    discount: '0',
  },
  {
    _id: 8,
    title: '진주 헤어핀 스타일링 5종 연예인 스타일 옆머리 고정삔 5종',
    img: 'image8.jpg',
    price: '54000',
    category: 'new',
    discount: '10',
  },
  {
    _id: 9,
    title: '14K/18K 르끌레어 리프 큐빅 일체형 목걸이',
    img: 'image9.jpg',
    price: '140000',
    category: 'new',
    discount: '10',
  },
  {
    _id: 10,
    title: '롤랑 앤 큐빅 헤어핀',
    img: 'image10.jpg',
    price: '8000',
    category: 'top',
    discount: '0',
  },
  {
    _id: 11,
    title: '롤랑 앤 큐빅 헤어핀',
    img: 'image10.jpg',
    price: '8000',
    category: 'top',
    discount: '0',
  },
];

let bannerList = [
  {
    _id: 3,
    title: '14k 데일리 심플 볼귀걸이 시리즈',
    img: 'image3.jpg',
    price: '30000',
    category: 'top',
    discount: '45',
    bannerImg: 'Img_bg1.jpg',
    bannerTitle: '이벤트 제목 1',
  },
  {
    _id: 11,
    title: '롤랑 앤 큐빅 헤어핀',
    img: 'image10.jpg',
    price: '8000',
    category: 'top',
    discount: '0',
    bannerImg: 'Img_bg3.jpg',
    bannerTitle: '이벤트 제목 3',
  },
  {
    _id: 9,
    title: '14K/18K 르끌레어 리프 큐빅 일체형 목걸이',
    img: 'image9.jpg',
    price: '140000',
    category: 'new',
    discount: '10',
    bannerImg: 'Img_bg2.jpg',
    bannerTitle: '이벤트 제목 2',
  },
];

export { list, bannerList };
